name: test
entities:
  - name: country
    properties:
      - name: "id"
        type: "sequence"
        index:
          id: 0
        constraints:
          - type: "interval"
            base: 3
            leap: 2
      - name: "name"
        type: "text"
        constraints:
          - type: size
            min: 5
            max: 20
      - name: "code"
        type: "text"
        constraints:
          - type: length
            max: 2
  - name: city
    properties:
      - name: "id"
        type: "sequence"
        index:
          id: 0
      - name: "name"
        type: "text"
        constraints:
          - type: size
            min: 5
            max: 100
      - name: "population"
        type: "number"
        constraints:
          - type: range
            min: 10000
            max: 200000
      - name: "km2"
        type: "number"
        constraints:
          - type: range
            min: 30
            max: 450
          - type: precision
            max: 2
      - name: "country"
        type: "sequence"
        reference:
          entity: "country"
          property: "id"
