name: test
entities:
  - name: country
    properties:
      - name: "id"
        type: "sequence"
        index:
          id: 0
        constraints:
          - type: "interval"
            base: 3
            leap: 2
      - name: "name"
        type: "text"
        constraints:
          - type: size
            min: 5
            max: 20
      - name: "code"
        type: "text"
        constraints:
          - type: length
            max: 2
  - name: city
    properties:
      - name: "id"
        type: "sequence"
        index:
          id: 0
      - name: "name"
        type: "text"
        constraints:
          - type: size
            min: 5
            max: 100
      - name: "population"
        type: "number"
        constraints:
          - type: range
            min: 10000
            max: 200000
      - name: "km2"
        type: "number"
        constraints:
          - type: range
            min: 30
            max: 450
          - type: precision
            max: 2
      - name: "country"
        type: "sequence"
        reference:
          entity: "country"
          property: "id"
  - name: "records"
    properties:
      - name: "id"
        type: "text"
        constraints:
          - type: "category"
            name: "id"
      - name: "city"
        type: "sequence"
        reference:
          entity: "city"
          property: "id"
      - name: "mayor"
        type: "text"
        constraints:
          - type: "category"
            name: "name"
      - name: "minister"
        type: "text"
        constraints:
          - type: "category"
            name: "name"
      - name: "vice-mayor"
        type: "text"
        constraints:
          - type: "category"
            name: "name"
            compoundId: 1
      - name: "refId"
        type: "text"
        constraints:
          - type: "category"
            name: "id"
            qualifier: "ref-##?##"
            compoundId: 1
      - name: "oos"
        type: "time"
        constraints:
          - type: "range"
            min: 36000
            max: 54000
      - name: "ooe"
        type: "time"
        constraints:
          - type: "correlation"
            properties: ["oos"]
            formula: "oos + 3600"

