name: "Release"
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: ${{ secrets.MAVEN_USERNAME }}
          server-password: ${{ secrets.MAVEN_PASSWORD }}
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      - name: Build with Maven
        run: mvn -B package -P release --file pom.xml
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          artifacts: "${{ github.workspace }}/data-conjurer/conjurer-shell/target/*.jar"
          bodyFile: "${{ github.workspace }}/release.md"
      - name: Publish to Maven Central
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            deploy