name: "Release"
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      - name: Build with Maven
        run: mvn package
#      - name: Create a Release
#        uses: ncipollo/release-action@v1
#        with:
#          artifactErrorsFailBuild: true
#          artifacts: "${{ github.workspace }}/conjurer-shell/target/data-conjurer-*.jar"
#          bodyFile: "${{ github.workspace }}/release.md"
      - name: create settings-security.xml
        run: |
          echo "<settingsSecurity>" > ~/.m2/settings-security.xml
          echo "  <master>${{ secrets.OSSRH_GPG_PASSPHRASE }}</master>" >> ~/.m2/settings-security.xml
          echo "</settingsSecurity>" >> ~/.m2/settings-security.xml
      - name: Publish to Maven Central
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSWORD: ${{ secrets.OSSRH_GPG_PASSPHRASE }}